config/routes.rb
Rails.application.routes.draw do
  resources :transactions do 
  	get :download_pdf, on: :collection
  	get :download_csv, on: :collection
  end
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'transactions#index'
  get 'transactions/new'
  get 'transactions/show'
  get 'transactions/edit'
  get 'user/index'
  get 'user/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense_transaction.rb
class ExpenseTransaction < Transaction
	
end

app/models/income_transaction.rb
class IncomeTransaction < Transaction
	
end

app/models/transaction.rb
require "csv"
class Transaction < ApplicationRecord
	belongs_to :user
  
  def self.to_csv(user_id)
    CSV.generate do |csv|
      csv << ['amount', 'description', 'type']
      where(user_id: user_id).each do |transaction|
        csv << [transaction.amount, transaction.description, transaction.type]
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :transactions      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


  def after_sign_in_path_for(resource)
   	root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = current_user.transactions
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = current_user.transactions.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = current_user.transactions.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transaction_url(@transaction), notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_path(@transaction), notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def download_pdf
   @transactions = current_user.transactions
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "transactions", layout: false   # Excluding ".pdf" extension.
      end
    end
  end

  def download_csv
    respond_to do |format|
      format.html
      format.csv { render text: Transaction.to_csv(current_user.id) }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = current_user.transactions.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:type, :description, :amount)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end
  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> 


    <title>Userinex</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="navbar-text pull-right">
  <% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

    <%= yield %>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(transaction.becomes(Transaction)) do |f| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %>
    
    <%= f.select :type,[['Income', 'IncomeTransaction'], ['Expense', 'ExpenseTransaction']]%>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/download_csv.csv.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
  </head>
  <body>
  User Id:<strong><%= current_user.email %></strong>.
  
    <div id="content">
      
      <table>
      <thead>
        <tr>
          <th>Type</th>
          <th>Description</th>
          <th>Amount</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.type %></td>
            <td><%= transaction.description %></td>
            <td><%= transaction.amount %></td>
            
          </tr>
        <% end %>


      </tbody>
    </table>
     <b>Total availabe balance:</b> <%= IncomeTransaction.where(user_id: current_user.id).sum(:amount) - ExpenseTransaction.where(user_id: current_user.id).sum(:amount).to_f %>


    </div>
  </body>
</html>

app/views/transactions/download_pdf.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />
  </head>
  <body>
  User Name:<strong><%= current_user.first_name %></strong>.
  
    <div id="content">
      
      <table>
      <thead>
        <tr>
          <th>Type</th>
          <th>Description</th>
          <th>Amount</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td><%= transaction.type %></td>
            <td><%= transaction.description %></td>
            <td><%= transaction.amount %></td>
            
          </tr>
        <% end %>


      </tbody>
    </table>
     <b>Total availabe balance:</b> <%= IncomeTransaction.where(user_id: current_user.id).sum(:amount) - ExpenseTransaction.where(user_id: current_user.id).sum(:amount).to_f %>


    </div>
  </body>
</html>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.type %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.amount %></td>
        <td><%= link_to 'Show', transaction_path(transaction) %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<b>Total availabe balance:</b> <%= IncomeTransaction.where(user_id: current_user.id).sum(:amount) - ExpenseTransaction.where(user_id: current_user.id).sum(:amount).to_f %>

<br>

<%= link_to 'New Transaction', new_transaction_path %>
<%= link_to 'Download PDF', download_pdf_transactions_path(format: :pdf) %>
<%= link_to 'Download CSV', download_csv_transactions_path(format: :csv) %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @transaction.type %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>



<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>

app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/user/new.html.erb
<h1>new</h1>